version: '2'

services:

    abp_mvc:
        image: monivault-api
        environment:
            - ASPNETCORE_ENVIRONMENT=Staging
        ports:
            - "21021:80"
        volumes:
            - "./Host-Logs:/app/App_Data/Logs"